### ISSUE TITLE
Admin resources tab doesn't show all the resources

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/biocollect#1429] opened 2022-06-21 01:33 UTC
The admin resources tab doesn't show all the resources.

Ex: https://biocollect-test.ala.org.au/acsa/project/index/19de564d-2a3c-403a-ab5d-ee0f58d1b646

<img width="794" alt="image" src="https://user-images.githubusercontent.com/72474143/174697865-33d00e58-cb4b-430f-973f-5f686469c669.png">

**Comment by chamaliperera512** [comment] 2022-06-22 02:37
This issue was only observed in https://biocollect-test.ala.org.au/acsa/project/index/19de564d-2a3c-403a-ab5d-ee0f58d1b646 project. This could not be reproduced in several other projects in TEST such as https://biocollect-test.ala.org.au/acsa/project/index/6f26b6eb-41cb-4776-a4f6-6d8294e955a5.
Hence this issue could not be reproduced.

**Comment by temi** [comment] 2022-06-22 02:53
@chamaliperera512 investigate the cause of this error. See if reindexing fixes it.

**Comment by temi** [comment] 2022-11-14 04:16
closing since it could not be reproduced.

**Closed by temi** 2022-11-14 04:16 UTC
Labels: Priority - medium
