### ISSUE TITLE
Project finder - Filters not working

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#1179] opened 2019-09-06 06:17 UTC
None of the filtering is working.

Select one and/or many facets, result set does not change.

Applies if selecting a single facet or refine for multi-select, also spatial filtering
Clear selections also not working

**Comment by patkyn** [comment] 2019-10-30 05:47
This seems to be working now. 

![image](https://user-images.githubusercontent.com/1606595/67832180-df048f80-fb34-11e9-8796-dd345f71d960.png)

**Comment by patkyn** [comment] 2019-10-30 05:48
I've also tried the spatial filtering, it seems ok.

**Comment by matilda2812** [comment] 2019-11-01 00:32
I also think this is working as intended on the first page. It doesn't work if any page after the first is selected before filtering, but this issue also occurs in grails2.

**Comment by matilda2812** [comment] 2020-03-04 00:34
Closing as this appears to be working

**Closed by matilda2812** 2020-03-04 00:34 UTC
Labels: Grails 3 upgrade
