### ISSUE TITLE
Ability to create site from the context of an activity 

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocollect#597] opened 2016-07-31 21:56 UTC

**Comment by pbrenton** [comment] 2017-03-15 03:30
Addition of map plugin to activity edit page is good, but needs the following

![image](https://cloud.githubusercontent.com/assets/8119351/23932400/da0fd234-098b-11e7-8a92-2b7664ef21f9.png)

**Comment by javier-molina** [comment] 2017-07-12 07:27
This is a duplicate of #619

**Closed by javier-molina** 2017-07-12 07:27 UTC
Labels: works
