### ISSUE TITLE
Works project type - Project plan tab display fixes

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/biocollect#640] opened 2016-08-12 00:53 UTC
1. Change page name from "MERI Plan Information" to "Project Plan Information"
2. Add table borders to all tables (1px solid). Also include appropriate padding between text and cell borders and highlight table headers with slightly darker background-color.

For example, see project https://biocollect-test.ala.org.au/works/project/index/fc0639d1-f9e5-4a26-ba4a-98d0985b6b91

**Comment by javier-molina** [comment] 2017-07-12 06:04
This is a duplicate of #858 already in peer review column

**Closed by javier-molina** 2017-07-12 06:04 UTC
Labels: bug, works
